SELECT 
    S.HACKER_ID, NAME 
FROM 
    HACKERS H ,
    SUBMISSIONS S,
    DIFFICULTY D, 
    CHALLENGES C 
WHERE 
    S.SCORE= D.SCORE 
    AND D.DIFFICULTY_LEVEL= C.DIFFICULTY_LEVEL 
    AND C.CHALLENGE_ID=S.CHALLENGE_ID 
    AND S.HACKER_ID= H.HACKER_ID
GROUP BY 
    S.HACKER_ID, 
    NAME 
HAVING 
    COUNT(S.CHALLENGE_ID)>1 
ORDER BY 
    COUNT(S.CHALLENGE_ID) DESC, H.HACKER_ID;
